steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kewarungimageml', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/kewarungimageml']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'kewarungserviceml', '--image', 'gcr.io/$PROJECT_ID/kewarungimageml', '--region', 'asia-southeast2', '--platform', 'managed', "--allow-unauthenticated"]

images :
- gcr.io/$PROJECT_ID/kewarungimageml

